import type { Metadata } from 'next';
import { AdminPageLayout } from '../../../../components/shared';
import { SectionCard } from '../../../../components/shared';
import { PromptTemplateBox } from '../../../../components/shared';
import { JsonImportClient } from './JsonImportClient';

export const metadata: Metadata = {
  title: 'Create Node',
};

export default async function NewNodePage({
  searchParams,
}: {
  searchParams: Promise<{ parentId?: string; type?: string }>;
}) {
  const params = await searchParams;
  const parentId = params.parentId ? parseInt(params.parentId, 10) : undefined;
  const nodeType = params.type as 'MUSEUM' | 'ROOM' | 'ARTIFACT' | undefined;
  return (
    <AdminPageLayout
      title="Create Node"
      breadcrumbs={[{ label: 'Admin', href: '/admin' }, { label: 'New' }]}
    >
      <div className="space-y-6">
        <SectionCard title="Instructions">
          <div className="space-y-3 text-fg">
            <p>
              Paste JSON generated by an LLM to create exactly one node (Museum,
              Room, or Artifact).
            </p>
            <p className="text-muted">
              Parent references must be included for Rooms and Artifacts.
              Nothing is saved until you confirm.
            </p>
          </div>
        </SectionCard>

        <SectionCard title="Prompt Templates">
          <div className="space-y-4">
            <PromptTemplateBox
              title="Create Museum"
              template={`{
  "type": "MUSEUM",
  "name": "British Museum",
  "knowledgeText": "The British Museum, located in London, is one of the world's oldest and most comprehensive museums. Founded in 1753, it houses a collection of over 8 million works spanning human history, culture, and art.",
  "furtherReading": [
    "https://www.britishmuseum.org/",
    "https://en.wikipedia.org/wiki/British_Museum"
  ]
}`}
              helperText="Include Wikipedia and museum website URLs. Provide historical context and notable collections."
            />

            <PromptTemplateBox
              title="Create Room"
              template={`{
  "type": "ROOM",
  "name": "Ancient Egypt Gallery",
  "parentId": 1,
  "knowledgeText": "This gallery showcases artifacts from ancient Egyptian civilization, including mummies, hieroglyphics, and funerary objects dating back thousands of years.",
  "furtherReading": [
    "https://www.britishmuseum.org/collection/galleries/ancient-egypt",
    "https://en.wikipedia.org/wiki/Ancient_Egypt"
  ]
}`}
              helperText="Include parentId (museum ID) or parentName. Describe the thematic focus and key artifacts on display."
            />

            <PromptTemplateBox
              title="Create Artifact"
              template={`{
  "type": "ARTIFACT",
  "name": "Rosetta Stone",
  "parentId": 2,
  "knowledgeText": "The Rosetta Stone is a granodiorite stele inscribed with three versions of a decree issued in Memphis, Egypt, in 196 BC. It was key to deciphering Egyptian hieroglyphs.",
  "furtherReading": [
    "https://www.britishmuseum.org/collection/object/Y_EA24",
    "https://en.wikipedia.org/wiki/Rosetta_Stone"
  ]
}`}
              helperText="Include parentId (room ID) or parentName. Provide physical description, historical significance, and discovery context."
            />
          </div>
        </SectionCard>

        <JsonImportClient parentId={parentId} nodeType={nodeType} />
      </div>
    </AdminPageLayout>
  );
}
