export const makeMuseum = (overrides: Record<string, unknown> = {}) => ({
  id: 1,
  name: 'Test Museum',
  slug: 'test-museum',
  wikidataId: 'Q123',
  wikipediaUrl: 'https://en.wikipedia.org/wiki/Test_Museum',
  image: null,
  coordinates: null,
  locationTags: [],
  citySlug: 'london',
  description: null,
  wikipediaSummary: null,
  officialWebsite: null,
  knowledgeText: null,
  furtherReading: [],
  museumHydratedAt: null,
  artifactsHydratedAt: null,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  ...overrides,
});

export const makeRoom = (overrides: Record<string, unknown> = {}) => ({
  id: 1,
  name: 'Test Room',
  slug: 'test-room',
  museumId: 1,
  parentRoomId: null,
  knowledgeText: null,
  furtherReading: [],
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  ...overrides,
});

export const makeArtifact = (overrides: Record<string, unknown> = {}) => ({
  id: 1,
  displayTitle: 'Test Artifact',
  localTitle: 'Test Artifact',
  localTitleLanguage: 'en',
  englishTitle: 'Test Artifact',
  rawPlaqueText: 'Raw plaque text',
  knowledgeTextEn: 'Knowledge text',
  slug: 'test-artifact',
  roomId: 1,
  museumId: 1,
  furtherReading: [],
  wikidataId: null,
  wikipediaUrl: null,
  wikimediaImageUrl: null,
  wikipediaSummary: null,
  wikipediaSummaryLang: null,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  ...overrides,
});

export const makeContent = (overrides: Record<string, unknown> = {}) => ({
  id: 1,
  text: 'Content text',
  type: 'introduction',
  artifactId: 1,
  museumId: null,
  roomId: null,
  llmProvider: 'google',
  model: 'gemini-2.5-flash',
  prompt: 'Test prompt',
  audioUrl: null,
  suggestedQuestions: [],
  isAdultContent: false,
  sensitiveTopics: [],
  subjectTags: [],
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  ...overrides,
});

export const makeQuestion = (overrides: Record<string, unknown> = {}) => ({
  id: 1,
  artifactId: 1,
  museumId: 1,
  roomId: 1,
  questionText: 'What is this artifact?',
  questionLanguage: 'en',
  normalizedQuestion: 'what is this artifact',
  questionHash: 'abc123',
  askedByUsername: 'prototype-tester',
  status: 'ACTIVE',
  askCount: 1,
  upvotes: 1,
  downvotes: 0,
  moderationBlocked: false,
  moderationCategories: [],
  moderationPayload: null,
  similarToQuestionId: null,
  answerText: 'This is a test artifact.',
  answerLanguage: 'en',
  answerAudioUrl: null,
  isAdultContent: false,
  sensitiveTopics: [],
  subjectTags: [],
  llmProvider: 'google',
  model: 'gemini-2.5-flash',
  prompt: 'Test prompt',
  promptVersion: '1.0',
  _count: { listenEvents: 0 },
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  ...overrides,
});

export const makeArtifactWithContext = (
  overrides: Record<string, unknown> = {}
) => ({
  ...makeArtifact(),
  museum: {
    id: 1,
    name: 'Test Museum',
    wikipediaSummary: null,
  },
  room: {
    id: 1,
    name: 'Test Room',
    museumId: 1,
    parentRoomId: null,
    parentRoom: null,
  },
  content: [],
  ...overrides,
});
