const MEBIBYTE = 1024 * 1024;
const BASE64_EXPANSION_FACTOR = 4 / 3;
const JSON_BODY_SAFETY_BUFFER_BYTES = 5 * MEBIBYTE;

export const DEFAULT_API_JSON_BODY_LIMIT_BYTES = 20 * MEBIBYTE;
export const PLAQUE_SCAN_MAX_IMAGE_BYTES = 60 * MEBIBYTE;

export const SCAN_API_JSON_BODY_LIMIT_BYTES = Math.ceil(
  PLAQUE_SCAN_MAX_IMAGE_BYTES * BASE64_EXPANSION_FACTOR +
    JSON_BODY_SAFETY_BUFFER_BYTES
);
