import type { Metadata } from 'next';
import { AdminPageLayout } from '../../../../components/shared';
import { SectionCard } from '../../../../components/shared';
import { PromptTemplateBox } from '../../../../components/shared';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { MuseumFormWrapper } from './MuseumFormWrapper';

export const metadata: Metadata = {
  title: 'Add Museum',
};

export default async function NewMuseumPage() {
  const museumTemplate = `{
  "name": "British Museum",
  "knowledgeText": "The British Museum, located in London, is one of the world's oldest and most comprehensive museums. Founded in 1753, it houses a collection of over 8 million works spanning human history, culture, and art.",
  "furtherReading": [
    "https://www.britishmuseum.org/",
    "https://en.wikipedia.org/wiki/British_Museum"
  ]
}`;

  return (
    <AdminPageLayout
      title="Add Museum"
      breadcrumbs={[
        { label: 'Admin', href: '/admin' },
        { label: 'Museums', href: '/admin?tab=museums' },
        { label: 'New Museum' },
      ]}
      actions={
        <Button asChild size="sm">
          <Link href="/admin">Back to Admin</Link>
        </Button>
      }
    >
      <div className="space-y-6 pb-24">
        {/* Instructions */}
        <SectionCard title="Instructions">
          <div className="space-y-3 text-primary">
            <p>
              Enter museum details manually using the form below, or paste JSON
              generated by an LLM to import the data.
            </p>
            <p className="text-muted-foreground">
              The name field is required. Knowledge text and further reading
              URLs are optional.
            </p>
          </div>
        </SectionCard>

        {/* Prompt Template */}
        <SectionCard title="Prompt Template">
          <PromptTemplateBox
            title="Create Museum"
            template={museumTemplate}
            helperText="Include Wikipedia and museum website URLs. Provide historical context and notable collections."
          />
        </SectionCard>

        {/* Museum Form */}
        <MuseumFormWrapper />
      </div>
    </AdminPageLayout>
  );
}
