import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { api } from '../../../../lib/api';
import { AdminPageLayout } from '../../../../components/shared';
import { SectionCard } from '../../../../components/shared';
import { PromptTemplateBox } from '../../../../components/shared';
import { JsonImportClient } from '../../nodes/new/JsonImportClient';
import { nodeEditHref } from '../../shared/nodeRoutes';
import Link from 'next/link';
import { Button } from '@/components/ui/button';

type Museum = {
  id: number;
  name: string;
  type: 'MUSEUM';
};

export const metadata: Metadata = {
  title: 'Add Room',
};

export default async function NewRoomPage({
  searchParams,
}: {
  searchParams: Promise<{ museumId?: string }>;
}) {
  const params = await searchParams;
  const museumId = params.museumId ? parseInt(params.museumId, 10) : undefined;

  if (!museumId) {
    redirect('/admin/nodes/new?type=ROOM');
  }

  // Fetch museum information
  let museum: Museum | null = null;
  try {
    const museumData = await api<Museum>(`/nodes/${museumId}`);
    if (museumData.type !== 'MUSEUM') {
      redirect('/admin/nodes/new?type=ROOM');
    }
    museum = museumData;
  } catch {
    redirect('/admin/nodes/new?type=ROOM');
  }

  // Create prompt template with museum information
  const roomTemplate = `{
  "type": "ROOM",
  "name": "Gallery Name",
  "parentId": ${museum.id},
  "parentName": "${museum.name}",
  "knowledgeText": "Describe this gallery room within ${museum.name}. Include the thematic focus, key artifacts or collections on display, historical context, and what visitors can expect to see.",
  "furtherReading": [
    "https://example.com/gallery-page",
    "https://en.wikipedia.org/wiki/Relevant_Topic"
  ]
}`;

  return (
    <AdminPageLayout
      title="Add Room"
      breadcrumbs={[
        { label: 'Admin', href: '/admin' },
        { label: 'Rooms', href: '/admin?tab=rooms' },
        { label: 'New Room' },
      ]}
      actions={
        <Button asChild size="sm">
          <Link href={nodeEditHref('MUSEUM', museum.id)}>
            Back to {museum.name}
          </Link>
        </Button>
      }
    >
      <div className="space-y-6">
        {/* Museum Context */}
        <SectionCard title="Adding Room To">
          <div className="space-y-2">
            <p className="text-lg font-semibold text-primary">{museum.name}</p>
            <p className="text-sm text-muted-foreground">
              This room will be added to the museum above.
            </p>
          </div>
        </SectionCard>

        {/* Instructions */}
        <SectionCard title="Instructions">
          <div className="space-y-3 text-primary">
            <p>
              Paste JSON generated by an LLM to create a new room for{' '}
              <strong>{museum.name}</strong>.
            </p>
            <p className="text-muted-foreground">
              The museum information has been pre-filled in the template below.
              You can copy the template and modify it with your LLM prompt, or
              paste JSON directly. Nothing is saved until you confirm.
            </p>
          </div>
        </SectionCard>

        {/* Prompt Template */}
        <SectionCard title="Prompt Template">
          <PromptTemplateBox
            title={`Create Room for ${museum.name}`}
            template={roomTemplate}
            helperText={`Include parentId (${museum.id}) or parentName ("${museum.name}"). Describe the thematic focus and key artifacts on display. The museum context is already included.`}
          />
        </SectionCard>

        {/* JSON Import */}
        <JsonImportClient nodeType="ROOM" museumId={museumId} />
      </div>
    </AdminPageLayout>
  );
}
