import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { api } from '../../../../lib/api';
import { AdminPageLayout } from '../../../../components/shared';
import { SectionCard } from '../../../../components/shared';
import { PromptTemplateBox } from '../../../../components/shared';
import { ArtifactFormClient } from './ArtifactFormClient';
import Link from 'next/link';
import { Button } from '@/components/ui/button';

type Museum = {
  id: number;
  name: string;
  type: 'MUSEUM';
};

type Room = {
  id: number;
  name: string;
  type: 'ROOM';
  parentId: number | null;
};

export const metadata: Metadata = {
  title: 'Add Artifact',
};

export default async function NewArtifactPage({
  searchParams,
}: {
  searchParams: Promise<{ museumId?: string; roomId?: string }>;
}) {
  const params = await searchParams;
  const museumId = params.museumId ? parseInt(params.museumId, 10) : undefined;
  const roomId = params.roomId ? parseInt(params.roomId, 10) : undefined;

  if (!museumId) {
    redirect('/admin');
  }

  // Fetch museum information
  let museum: Museum | null = null;
  try {
    const museumData = await api<Museum>(`/nodes/${museumId}`);
    if (museumData.type !== 'MUSEUM') {
      redirect('/admin');
    }
    museum = museumData;
  } catch {
    redirect('/admin');
  }

  // Fetch rooms for this museum
  let rooms: Room[] = [];
  try {
    rooms = await api<Room[]>(`/admin/nodes/rooms?museumId=${museumId}`);
  } catch {
    // Continue without rooms
  }

  // If roomId is provided, fetch that room
  let selectedRoom: Room | null = null;
  if (roomId) {
    try {
      const roomData = await api<Room>(`/nodes/${roomId}`);
      if (roomData.type === 'ROOM' && roomData.parentId === museumId) {
        selectedRoom = roomData;
      }
    } catch {
      // Room not found or invalid
    }
  }

  // Create prompt template with museum and room information
  const artifactTemplate = selectedRoom
    ? `{
  "type": "ARTIFACT",
  "name": "Artifact Name",
  "parentId": ${selectedRoom.id},
  "parentName": "${selectedRoom.name}",
  "knowledgeText": "Describe this artifact in the ${selectedRoom.name} room of ${museum.name}. Include physical description, historical significance, discovery context, and cultural importance.",
  "furtherReading": [
    "https://example.com/artifact-page",
    "https://en.wikipedia.org/wiki/Relevant_Topic"
  ]
}`
    : `{
  "type": "ARTIFACT",
  "name": "Artifact Name",
  "parentName": "Room Name",
  "museumId": ${museum.id},
  "museumName": "${museum.name}",
  "knowledgeText": "Describe this artifact. Include physical description, historical significance, discovery context, and cultural importance. If the room doesn't exist, it will be created automatically.",
  "furtherReading": [
    "https://example.com/artifact-page",
    "https://en.wikipedia.org/wiki/Relevant_Topic"
  ]
}`;

  return (
    <AdminPageLayout
      title="Add Artifact"
      breadcrumbs={[
        { label: 'Admin', href: '/admin' },
        { label: 'Artifacts', href: '/admin?tab=artifacts' },
        { label: 'New Artifact' },
      ]}
      actions={
        <Button asChild size="sm">
          <Link href={`/admin/museums/${museum.id}`}>
            Back to {museum.name}
          </Link>
        </Button>
      }
    >
      <div className="space-y-6">
        {/* Museum Context */}
        <SectionCard title="Adding Artifact To">
          <div className="space-y-2">
            <p className="text-lg font-semibold text-primary">{museum.name}</p>
            {selectedRoom && (
              <p className="text-sm text-muted-foreground">
                Room: <strong>{selectedRoom.name}</strong>
              </p>
            )}
            {!selectedRoom && (
              <p className="text-sm text-muted-foreground">
                This artifact will be added to a room. If the room doesn't exist
                yet, it will be created automatically.
              </p>
            )}
          </div>
        </SectionCard>

        {/* Instructions */}
        <SectionCard title="Instructions">
          <div className="space-y-3 text-primary">
            <p>
              Enter artifact details manually using the form below, or paste
              JSON generated by an LLM to import the data.
            </p>
            <p className="text-muted-foreground">
              {selectedRoom
                ? `The room "${selectedRoom.name}" has been pre-filled.`
                : "You can specify a room by name (parentName) or ID (parentId). If the room doesn't exist, it will be created automatically."}
            </p>
            <p className="text-sm text-muted-foreground">
              If you import JSON that conflicts with existing form data, you'll
              be able to choose which values to keep for each field.
            </p>
          </div>
        </SectionCard>

        {/* Available Rooms */}
        {rooms.length > 0 && (
          <SectionCard title="Available Rooms">
            <div className="space-y-2">
              <p className="text-sm text-muted-foreground">
                You can reference these existing rooms by name or ID:
              </p>
              <ul className="list-disc list-inside space-y-1 text-sm">
                {rooms.map((room) => (
                  <li key={room.id}>
                    <span className="font-medium">{room.name}</span> (ID:{' '}
                    {room.id})
                  </li>
                ))}
              </ul>
            </div>
          </SectionCard>
        )}

        {/* Prompt Template */}
        <SectionCard title="Prompt Template">
          <PromptTemplateBox
            title={selectedRoom ? `in ${selectedRoom.name}` : ''}
            template={artifactTemplate}
            instructions={`I'm building a database of artifacts in museums, below is an example of the data structure I need:

{{JSON}}

The "knowledgeText" should be exactly the same as what you would read on the plaque, if you have this information, please only use what is on the plaque, but if you don't have that information it is ok to speculate as to what you would expect to see on the plaque and we can update it later. Please specify if this is exactly right or if you are speculating, to be clear, the only time you would get it exactly right is if in this prompt there is an image of the plaque or a quote of the plaque.

The "furtherReading" should be trusted and relevant sources you can find about the specific artifact, ideally from the museum's website or Wikipedia or similar.

The information about the artifact I want to add is below, please search and try to double check to make sure that the information in the JSON you return is accurate.`}
          />
        </SectionCard>

        {/* Artifact Form */}
        <ArtifactFormClient
          museumId={museumId}
          museumName={museum.name}
          rooms={rooms}
          roomId={roomId}
          initialParentName={selectedRoom?.name}
        />
      </div>
    </AdminPageLayout>
  );
}
